name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ecs-lint:
    runs-on: ubuntu-latest
    name: Lint PHP with ECS (EasyCodingStandard)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-scripts

      - name: Run ECS (EasyCodingStandard)
        run: php vendor/bin/ecs check src

  test:
    needs: ecs-lint
    runs-on: ubuntu-latest
    name: Run PHPUnit Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.10.2
          sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker containers
        run: docker-compose up -d --build

      - name: Install Composer dependencies
        run: docker-compose exec api composer install --no-scripts

      - name: Initialize database
        run: |
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:database:drop --force --if-exists"
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:database:create"
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:migrations:migrate"
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:fixtures:load"

      - name: Run PHPUnit
        run: docker-compose exec api php vendor/bin/phpunit --no-coverage

      - name: Tear down Docker containers
        if: always()
        run: docker-compose down
