name: Lint PHP with Composer and ECS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.10.2
          sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker containers
        run: docker-compose up -d --build

      - name: Install Composer dependencies
        run: docker-compose exec api composer install --no-scripts

      - name: Run ECS (EasyCodingStandard)
        run: docker-compose exec api php vendor/bin/ecs check src

      - name: Initialize database
        run: |
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:database:drop --force --if-exists"
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:database:create"
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:migrations:migrate"
          docker-compose exec api sh -c "php bin/console --env=test --no-interaction doctrine:fixtures:load"
          docker-compose exec api sh -c "php vendor/bin/phpunit --no-coverage"

      - name: Run PHPUnit
        run: docker-compose exec api ./vendor/bin/phpunit --configuration phpunit.xml

      - name: Tear down Docker containers
        if: always()
        run: docker-compose down
